fix workflow

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -20,6 +20,34 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y curl jq
 
+    - name: Run server
+      run: |
+        # Determine the file type
+        if [ -f server.js ]; then
+          echo "Running server.js"
+          node server.js &
+          server_pid=$!
+        elif [ -f server.go ]; then
+          echo "Running server.go"
+          go run server.go &
+          server_pid=$!
+        elif [ -f server.py ]; then
+          echo "Running server.py"
+          python server.py &
+          server_pid=$!
+        elif [ -f server.c ]; then
+          echo "Running server.c"
+          gcc server.c -o server
+          ./server &
+          server_pid=$!
+        else
+          echo "Server file not found."
+          exit 1
+        fi
+
+        # Add a small delay to allow the server to start before running tests
+        sleep 5
+
     - name: Run tests for modified exercise folders
       run: |
         modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
